# Generated by Django 5.0.6 on 2024-06-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(to='AppCoder.curso'),
        ),
    ]
