# Generated by Django 5.0.6 on 2024-06-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_profesor_cursos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('nombre', 'camada'), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'camada')},
        ),
    ]
