# Generated by Django 5.0.6 on 2024-06-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_curso_options_alter_curso_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(to='AppCoder.curso'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='profesores',
            field=models.ManyToManyField(to='AppCoder.profesor'),
        ),
    ]
